version: '3.7'

services:
  currency-exchange:
    image: eyouu/microservices-currency-exchange-service:0.0.2-SNAPSHOT
    ports:
      - '8000:8000'
    networks:
      currency-network:
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      # Overrides property in application.properties since localhost in docker != localhost on user env, so we use naming
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka:
      SPRING.ZIPKIN.BASE_URL:http=//zipkin-server:9411/:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  currency-conversion:
    image: eyouu/microservices-currency-conversion-service:0.0.2-SNAPSHOT
    ports:
      - '8100:8100'
    networks:
      currency-network:
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka:
      SPRING.ZIPKIN.BASE_URL=http://zipkin-server:9411/:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  api-gateway:
    image: eyouu/microservices-api-gateway:0.0.2-SNAPSHOT
    ports:
      - '8765:8765'
    networks:
      currency-network:
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka:
      SPRING.ZIPKIN.BASE_URL:http://zipkin-server:9411/:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  zipkin-server:
    image: openzipkin/zipkin:2.21
    ports:
      - '9411:9411'
    networks:
      currency-network:
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672

  rabbitmq:
    image: rabbitmq:3.8.12-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      currency-network:

  naming-server:
    image: eyouu/microservices-naming-server:0.0.1-SNAPSHOT
    ports:
      - '8761:8761'
    networks:
      currency-network:

networks:
  currency-network: